### ISSUE TITLE
Mistake identification question

### ISSUE THREAD

**Issue by jcklie** [ZihanWangKi/CrossWeigh#10]
Hello,
regarding the Label Mistake Identification Results (4.4), when did you flag an instance an error? If it was at least one iteration disagreeing with the original label or majority or ...?
Thanks!

**Comment by ZihanWangKi** [comment]
Hi,

The count of mistakes was identified over an average of the 3 iterations. If one model identified a mistake correctly, and the other two did not, this counts as a 0.33 in the final score.

**Comment by jcklie** [comment]
So if I wanted to use CrossWeigh to find errors in a dataset, would I use one iteration of 10-fold CV with entity filtering and flag disagreements as errors or would I run it 3 times and then aggregate disagreements somehow, like you did for reweighing (at least one, majority, all) to obtain a binary mistake/no mistake error?

**Comment by ZihanWangKi** [comment]
My feeling is that running 3 times (and majority voting) usually has some improvement on detecting errors over just once, as the NER model does have some degree of instability. However, doing it once should also be fine, for the sake of efficiency.

**Comment by jcklie** [comment]
Thanks for the quick reply!
