### ISSUE TITLE
Missing requirements.txt file 

### ISSUE THREAD

**Issue by uahmad235** [ZihanWangKi/CrossWeigh#5]
Can you please attach the requirements.txt file since it is very difficult to run code without knowing exact versions of dependencies e.g., flair, pytorch.

**Comment by ZihanWangKi** [comment]
Thanks for pointing this out! Due to a force update in flair (the old paths are not accessible), I have updated the code in this [pr](https://github.com/ZihanWangKi/CrossWeigh/pull/7) to accommodate with flair 0.7. Please check it out and let me know if it works!
