### ISSUE TITLE
License for CONLL++

### ISSUE THREAD

**Issue by manojpamk** [ZihanWangKi/CrossWeigh#8]
Hi,

Is there a license to use CONLL++

**Comment by ZihanWangKi** [comment]
Hi,
Sorry for the late reply. I have added the Apache 2.0 license. Let me know if there are further concerns.

**Comment by David-Lee-1990** [comment]
hi, i find the test dataset here is different with the data here https://github.com/pfliu-nlp/Named-Entity-Recognition-NER-Papers/tree/master/ner_dataset/CoNLL%2B%2B, why?

**Comment by ZihanWangKi** [comment]
Hi,

There was a bug when handling the DOCStart tokens such that they are placed in an incorrect position (if you remove all the DOCSTART lines from both files they should be the same). A fix was pushed on this repo (https://github.com/ZihanWangKi/CrossWeigh/pull/4) but seems that I forgot to update this fix into the other repos. Let me do it now. The test set in this repo is correct.
