### ISSUE TITLE
Using this model for other languages

### ISSUE THREAD

**Issue by appledora** [ZihanWangKi/CrossWeigh#9]
Hello, I am trying to run this repo for Bengali data formatted like conLL dataset. Where do I have to make the changes?

**Comment by ZihanWangKi** [comment]
Hello,

I anticipate mostly no changes during creating the entity disjoint splits --- you can also monitor and check the created data to see if anything unusual happens. For the NER training part (both an unweighted version and a weighted version), you may use [flair](https://github.com/flairNLP/flair), which is what is used in the repo, but you might need to consult with them on how their language models handle non-latin characters. You can also plug in other NER models as well.
